### ISSUE TITLE
issue with 2 virtual scroll if we  use scrollbar of same parent block

### ISSUE THREAD

**Issue by Ts-alan** [rintoj/ngx-virtual-scroller#192] opened 2018-04-19 09:58 UTC
I use 2 virtual scroll with same scrollbar of parent block

The first virtual scroll

     <virtual-scroll
      [items]="watchlist.items"
      [parentScroll]="scrollingBlock.nativeElement"
      (update)="viewPortItems = $event">
        <app-watchlist-market
          *ngFor="let watchlistItem of viewPortItems; trackBy: watchlistTrackByFn"
          [attr.watchlistId]="watchlist.watchlistId"
          [attr.marketId]="watchlistItem.marketId"
          [watchlistItem]="watchlistItem"
          [curated]="watchlist.popularMarkets"
          [scrollingWatchlists]="scrollingWatchlists"
          (marketRemovedFromWatchlist)="handleMarketRemovedFromWatchlist($event)">
        </app-watchlist-market>
    </virtual-scroll>

The second virtual scroll

       <virtual-scroll
      [items]="watchlist.items"
      [parentScroll]="scrollingBlock.nativeElement"
      (update)="popularViewPortItems = $event">
        <app-watchlist-market
          *ngFor="let watchlistItem of popularViewPortItems"
          [attr.watchlistId]="watchlist.watchlistId"
          [attr.marketId]="watchlistItem.marketId"
          [watchlistItem]="watchlistItem"
          [curated]="watchlist.popularMarkets"
          [scrollingWatchlists]="scrollingWatchlists">
        </app-watchlist-market>
    </virtual-scroll>

When i scroll in this situation i have following issue
![image](https://user-images.githubusercontent.com/9947228/38985076-0a7b3aa0-43d1-11e8-9601-a014eca02f81.png)
I have gap in the second virtual scroll.If i delete first virtual scroll-all work fine.Any  ideas?

**Comment by speige** [comment] 2018-07-21 08:18
Would you mind creating a stackblitz of this issue to help me troubleshoot it? Thanks.

**Comment by speige** [comment] 2018-08-02 18:17
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Comment by imamy4** [comment] 2018-08-15 10:29
I have the same problem. I created example on [stackblitz](https://stackblitz.com/edit/angular-sxt8pd-uuuvwz). 
The problem occurs when I put parent container to div element with `position: absolute`.

**Comment by speige** [comment] 2018-08-15 11:18
Re-opening. I'll try to look at the stackblitz when I have time. Thanks for submitting it.

If anyone else has a chance to help troubleshoot this, please do.

**Comment by speige** [comment] 2018-08-15 19:04
@imamy4 

Remove [childHeight]="20" and it works fine.  Your elements were actually 22px (on my box), so the last few items were being cut off.
The purpose of that property was for variable-height children. If they're all the same size it's not necessary.

The childHeight property is now deprecated & has been replaced by enableUnequalChildrenSizes. If your real app has variable-height children, I suggest using that instead.

I also think your [parentScroll]="parent" should be [parentScroll]="parent.nativeElement", but I didn't actually test it & surprisingly it seems to work fine as is.

Closing this. Please re-open if you think it's still an issue.

**Comment by imamy4** [comment] 2018-08-16 11:39
@speige 

I removed `[childHeight]` from example and it doesn't work yet =)
You can see by the example that first few items of the second scroll were cut off.

We see the last items of the first scroll and the first items of the second scroll:
![image](https://user-images.githubusercontent.com/3244960/44205767-2a18c980-a160-11e8-8f73-b45f35a860b4.png)
After scrolling to the second scroll items disappear.
![image](https://user-images.githubusercontent.com/3244960/44205784-40268a00-a160-11e8-8688-63da4a917973.png)

> The childHeight property is now deprecated & has been replaced by enableUnequalChildrenSizes.

This doesn't work for me when I use a table with borders, perhaps it is a bug. I will try to create an example with reproducing.

> I also think your [parentScroll]="parent" should be [parentScroll]="parent.nativeElement", but I didn't actually test it & surprisingly it seems to work fine as is.

And I thought so too =) But `parent` in template is a div node, not an `ElementRef`

**Comment by speige** [comment] 2018-08-16 14:08
My mistake, I guess you only need .nativeElement if the templateRef is a custom component.

I thought I had it working earlier by only removing [childHeight]="20", but maybe I also changed something else that I forgot.

Today when I tried the issue was still happening, however removing both [childHeight]="20" and [parentScroll]="parent" (or removing "parentScroll ||" and leaving "scroll.window" ) fixed it.

You're correct that you need to use [childHeight] with a table. Unfortunately the virtual-scroll code doesn't know how to measure tables correctly. In that case use [childHeight]="22" instead of [childHeight]="20" and it works (because 20 was the wrong size).

Let me know if that's still not working.

I'll try to research why virtual-scroll can't measure tables correctly.

**Comment by speige** [comment] 2018-08-16 14:10
I'm also not sure why setting parentScroll to the div instead of window doesn't work. I should research that too.

**Comment by imamy4** [comment] 2018-08-16 14:43
@speige, thanks for your answer.

The big problem for me is the inability to use custom div as the parent scroll. 
The problem with tables size measuring has a workaround, the problem with parent scroll no, unfortunately =)

**Comment by speige** [comment] 2018-08-16 14:51
Makes sense. I'll re-open this ticket.

Just curious, why does the window scroll workaround not work in your scenario?

**Comment by imamy4** [comment] 2018-08-16 15:12
> Just curious, why does the window scroll workaround not work in your scenario?

Because I have several divs on one page that are parent scrolls.

**Comment by speige** [comment] 2018-09-18 17:34
@imamy4 I've updated the documentation with an HTML table example that doesn't require ChildWidth/ChildHeight to be set:

```
<virtual-scroll #scroll [items]="myItems">
	<table>
		<thead>
			<th>Index</th>
			<th>Name</th>
			<th>Gender</th>
			<th>Age</th>
			<th>Address</th>
		</thead>
		<tbody #container>
			<tr *ngFor="let item of scroll.viewPortItems">
				<td>{{item.index}}</td>
				<td>{{item.name}}</td>
				<td>{{item.gender}}</td>
				<td>{{item.age}}</td>
				<td>{{item.address}}</td>
			</tr>
		</tbody>
	</table>
</virtual-scroll>
```

Can you try this in combination with our previous discussion to see if it resolves anything?

**Comment by imamy4** [comment] 2018-10-31 17:32
@speige I tried, but nothing has changed. Problem is still reproduced.

**Comment by speige** [comment] 2018-10-31 17:52
@imamy4 could you update your stackblitz to match your use case exactly? I believe it's using divs whereas your actual code is using tables.

**Comment by imamy4** [comment] 2019-01-23 11:39
Error doesn't reproduce on version ngx-virtual-scroller@1.0.16. You can check example [stackblitz](https://stackblitz.com/edit/angular-sxt8pd-uuuvwz).

**Comment by speige** [comment] 2019-05-14 20:19
Closing this as it appears to be resolved & OP hasn't updated the issue.

**Closed by speige** 2019-05-14 20:19 UTC
