### ISSUE TITLE
Loading in chunks doesn't work with scroll to index

### ISSUE THREAD

**Issue by tamtakoe** [rintoj/ngx-virtual-scroller#331] opened 2019-05-21 15:26 UTC
See your example. If you click `scroll to index 50` you just load next chunk but not chunk with the index 50

**Comment by speige** [comment] 2019-05-21 16:42
Closing. This is not a bug.

"Loading in Chunks" is not a special feature of this component, it's something you can easily code yourself. The demo shows an extremely simplistic way of how you can code it. You need to determine how to code it for your particular app.

Because "Loading in Chunks" isn't a built-in feature, none of the apis behave differently based on it . If there are 50+ items, "Scroll to Index" will scroll to the 50th. If there are less, it will scroll to the last item. The naive "Loading in Chunks" example downloads new randomly generated items any time the scroll position reaches the end.

If you want "Loading in Chunks" to behave differently in your app, you'll need to determine how to code it on your own.

Good luck!

**Closed by speige** 2019-05-21 16:42 UTC

**Comment by tamtakoe** [comment] 2019-05-22 14:10
I need to load item with index 50 and its siblings if I scroll to index 50. It means I can have gaps in my virtual data and scroll should work correct. I hope it is possible

**Comment by speige** [comment] 2019-05-22 18:00
As I said previously, "Loading in Chunks" is not a built-in feature of the library. It is something you have to code yourself. The example shows an easy theoretical way to do it. Obviously what you're mentioning is possible, but it's your responsibility to figure out how to code it.
