### ISSUE TITLE
How does container resizing actually work?

### ISSUE THREAD

**Issue by Nirco96** [rintoj/ngx-virtual-scroller#295] opened 2019-01-30 12:19 UTC
Hello, first of all I want to thank you very much for the virtual scroller, it works wonderfully (even better than the NgMaterial one) and I love it. 

I have a question about how the scroller actually checks whether the container was resized? I'm using the scroller in combination with jQuery UI resizable(), and since the scroller's container resizes, I had to set the checkResizeInterval to around 50 for it to refresh fast enough so I don't see any "blank" spaces before the scroll resizes. I was wondering though, does it actually poll the scroller every 50 milis even when "idle"? There's an option to attach a callback to the resize() event of the jQuery ui resizeable and then maybe call the refresh() method of the virtual scroll so it only recalculates when the container actually resizes. Which do you think is better?

Thank you very much!

**Comment by speige** [comment] 2019-01-30 16:09
The virtual-scroller auto-resize-detection should be working.

Yes, the [checkResizeInterval]="50" will run every 50ms even when idle. It could theoretically cause performance problems, you'll have to test that for yourself because it's application-specific. The issue is that javascript doesn't have any built-in DOM resize event, so it has to be done via a setInterval & calling domElement.getBoundingClientRect.

An alternative is:
[checkResizeInterval]="0" and calling virtualScroller.resize() any time the jQuery callback notifies you of a resize. You can also try setTimeout(() => virtualScroller.resize(), 0) on the jQuery callback to see if it works better (which delays virtualScroller's rendering until jQuery is finished rendering);

I don't know which option is better for your application, however I would guess using the jQuery callback would be better/smoother because it'd know exactly when it needed to refresh rather than checking every 50ms to see if a resize occurred or not. Try both & see which feels smoother for your application.


Closing since this is a question, not an issue.

**Closed by speige** 2019-01-30 16:09 UTC
