### ISSUE TITLE
Prevent current scroll position jump after unshifting new items

### ISSUE THREAD

**Issue by max-che** [rintoj/ngx-virtual-scroller#301] opened 2019-02-08 09:49 UTC
Set scroll not to the end nor a start of the list to see this clearly.
After new items added to the beginning of the scrollable list by `unshift`-ing the array you would see whole list moved down by the height of the new items.
It would be great if current scroll position will remain the same. Or to have an option to do this.

Thank you for this great component! It realy helped me out to deal with large amount of items.
PS: i'm implementing mesenger web client for my app at the moment, using ngx-virtual-scroller + perfect-scrollbar(as directive)

**Comment by dimagrytsan1995** [comment] 2019-03-01 11:36
This code is not perfect, but it solves this problem.

`
public old_scroll_height;
  public old_scrollTop;

  onListChange(event: ChangeEvent) {
    const scrollHeight = document.getElementsByClassName('total-padding')[0].scrollHeight;
    if (this.firstChatLoad) {
      this.virtualScroller.scrollToPosition(9999, null, () => this.firstChatLoad = false);
    } else {
      if (this.old_scroll_height !== scrollHeight && this.loadingTop) {
        console.log(this.old_scroll_height + ' scroll_height ---> ' + scrollHeight);
        // document.getElementById('scrollingBlock').scrollTop = this.old_scroll_height + event.scrollStartPosition;
        this.virtualScroller.scrollToPosition(this.old_scroll_height + event.scrollStartPosition, 0, () => this.loadingTop = false);
      }


      if (!this.loadingTop && event.start == 0 && this.messagesObject['total'] !== this.messages.length) {

        this.loadingTop = true;

        this.callGetChatsMessages('top')
          .then((res) => this.setMessages = [...res.objects, ...this.messages])
          .catch(() => this.loadingTop = false);  
      }

      this.old_scroll_height = scrollHeight;
      this.old_scrollTop = document.getElementById('scrollingBlock').scrollTop;
    } 
  }
`

**Comment by dimagrytsan1995** [comment] 2019-03-01 11:39
This code is not perfect, but it solves this problem.
```
public old_scroll_height;
  public old_scrollTop;

  onListChange(event: ChangeEvent) {
    const scrollHeight = document.getElementsByClassName('total-padding')[0].scrollHeight;
    if (this.firstChatLoad) {
      this.virtualScroller.scrollToPosition(9999, null, () => this.firstChatLoad = false);
    } else {

      if (this.old_scroll_height !== scrollHeight && this.loadingTop) {
        this.virtualScroller.scrollToPosition(this.old_scroll_height + event.scrollStartPosition, 0, () => this.loadingTop = false);
      }

      this.old_scroll_height = scrollHeight;
      this.old_scrollTop = document.getElementById('scrollingBlock').scrollTop;
    }
  }

```

**Comment by Kartheek2016** [comment] 2019-03-28 14:35
I've tried two examples, Can anyone let me know how to fix this issue.

**Comment by Kartheek2016** [comment] 2019-03-28 14:38
> Set scroll not to the end nor a start of the list to see this clearly.
> After new items added to the beginning of the scrollable list by `unshift`-ing the array you would see whole list moved down by the height of the new items.
> It would be great if current scroll position will remain the same. Or to have an option to do this.
> 
> Thank you for this great component! It realy helped me out to deal with large amount of items.
> PS: i'm implementing mesenger web client for my app at the moment, using ngx-virtual-scroller + perfect-scrollbar(as directive)

sdafsdaf

**Comment by speige** [comment] 2019-04-05 21:05
Please create a StackBlitz to demonstrate the issue.

**Comment by skadecl** [comment] 2019-05-13 15:48
Any updates on this?

I am facing the same issue. If @speige could provide a little orientation I will gladly help fix this and raise a PR.

Thanks a lot!

**Comment by speige** [comment] 2019-05-14 06:13
@Kartheek2016 Sorry, I had asked for a StackBlitz earlier but missed the notification when you edited your comment.

I believe this is a good feature to add. It's not currently built-in.

@skadecl I think this is an easy change. I'm glad to accept a PR, but I think it'll be easier for me to fix it than to explain how the code works :) I'll try to code something up soon. If you figure it out before me, let me know. Thanks!

**Comment by speige** [comment] 2019-05-14 21:17
I updated the samples in the demo at https://rintoj.github.io/ngx-virtual-scroller to have use cases for prepending items so we can test easily while attempting to fix this.

@skadecl 
I tried coding a solution, but it didn't seem to work. I'm going to take a break & mess with it again later.

Here's my attempt if you want to play around with it. Most of it is existing code, I surrounded the new code in comments.

```
	protected calculateViewport(): IViewport {
		let dimensions = this.calculateDimensions();
		let offset = this.getElementsOffset();

		let scrollStartPosition = this.getScrollStartPosition();

// new code
		//if items were prepended, scroll forward to keep same items visible
		if (this.previousViewPort) {
			let scrollLengthDelta = dimensions.scrollLength - this.previousViewPort.scrollLength;
			if (scrollLengthDelta > 0 && this.viewPortItems) {
				let oldStartItem = this.viewPortItems[0];
				let oldStartItemIndex = this.items.findIndex(x => this.compareItems(oldStartItem, x));
				if (oldStartItemIndex > this.previousViewPort.startIndexWithBuffer) {
					let itemOrderChanged = false;
					for (let i = 1; i < this.viewPortItems.length; ++i) {
						if (!this.compareItems(this.items[oldStartItemIndex + i], this.viewPortItems[i])) {
							itemOrderChanged = true;
							break;
						}
					}
					if (!itemOrderChanged) {
						scrollStartPosition += scrollLengthDelta;
					}
				}
			}
		}
// end new code

		if (scrollStartPosition > (dimensions.scrollLength + offset) && !(this.parentScroll instanceof Window)) {
			scrollStartPosition = dimensions.scrollLength;
		} else {
			scrollStartPosition -= offset;
		}
		scrollStartPosition = Math.max(0, scrollStartPosition);

		let pageInfo = this.calculatePageInfo(scrollStartPosition, dimensions);
		let newPadding = this.calculatePadding(pageInfo.startIndexWithBuffer, dimensions);
		let newScrollLength = dimensions.scrollLength;

		return {
			startIndex: pageInfo.startIndex,
			endIndex: pageInfo.endIndex,
			startIndexWithBuffer: pageInfo.startIndexWithBuffer,
			endIndexWithBuffer: pageInfo.endIndexWithBuffer,
			padding: Math.round(newPadding),
			scrollLength: Math.round(newScrollLength),
			scrollStartPosition: pageInfo.scrollStartPosition,
			scrollEndPosition: pageInfo.scrollEndPosition,
			maxScrollPosition: pageInfo.maxScrollPosition
		};
	}
}

```

**Comment by speige** [comment] 2019-05-15 00:08
This is tentatively fixed in npm version 2.2.0. Please try it out & let me know what you think.

There is a minor flicker when new items are prepended because it temporarily scrolls up & then back down.

Code Explanation:
Virtual-Scroller isn't able to measure any invisible items, it has to render them on the screen to measure them. All invisible items have estimated measurements only. For this reason, the math calculations can be incorrect sometimes. To correct this, it recursively re-calculates & re-renders several times until it finds an equilibrium where the previous calculations were close-enough. Typically this happens when an invisible item becomes visible for the first time.

The code I posted earlier should have fixed this issue without any flicker, however in debugging I found that as it kept re-rendering it forgot the original scroll position it was trying to preserve. The new code waits until it finds the equilibrium & then afterwards scrolls to the correct position.

I'll keep this open until I find a better solution. I feel like the original implementation should have worked, but I wasn't in the mood for intense debugging to find the root cause of the bug.

**Comment by skadecl** [comment] 2019-05-15 00:12
I'll dive into it and try to figure out the flickering. But probably next weekend, that's when I will have some time to give it a try.

Thanks a lot! I will keep you updated if a come up with something.

**Comment by speige** [comment] 2019-05-15 21:01
There was a complaint about a breaking change in npm version 2.2.0, so I moved this to version 3.0.0

**Comment by jbonet** [comment] 2019-06-03 08:40
This is still happening, any news?

**Comment by speige** [comment] 2019-06-03 08:52
@jbonet Can you clarify? This was tentatively fixed & can be tested via the demo at https://rintoj.github.io/ngx-virtual-scroller

The only concern I had was it has a minor flicker.

However, I am now noticing on the demo site that with the "Toggle Random Height" button (enableUnequalChildrenSizes) the issue remains.

Are you doing differing height child items? If not, can you create a stackblitz to demonstrate the issue you're seeing?

Unfortunately I'm not sure when I'll have time to fix this one. Any help that can be offered with a pull request would be great. Thanks.

**Comment by jbonet** [comment] 2019-06-03 08:54
Steps to reproduce:

https://rintoj.github.io/ngx-virtual-scroller/parentScroll

- Reduce items to 0.
- Append 10 items.
- Prepend 10 items. -> Scroll jumps.

**Comment by speige** [comment] 2019-06-03 09:03
Strange. On my box those steps work perfectly fine.
What browser are you using? 
Can you post a video of it happening?

I sometimes get a "flicker", where it temporarily scrolls to the wrong place & immediately scrolls back to the correct place. That was caused by my hacky fix for this issue. We need to come up with a better permanent fix.

**Comment by jbonet** [comment] 2019-06-03 09:12
I am using Chrome 74 on Windows 10.

It happens on Android Chrome too.

Here is a video of this: https://youtu.be/zfDQFXhpUb4

**Comment by speige** [comment] 2019-06-03 11:34
@jbonet 
I must be confused. When you append items The top item # is 10000 Amelia Cummings. After you prepend, it's still focused on the same item. If you want to see the newly prepended items, you have to scroll up.

I believe this is the intended behavior based on what was requested in this issue. The behavior was different in previous versions, this new behavior was released with version 3.0

To avoid this, you could call scrollToItem or scrollToIndex after you prepend new items. I could also add a flag to prevent this behavior if a lot of people dislike it.

**Comment by jbonet** [comment] 2019-06-03 11:52
Well from the title I thought that if scroll was at its initial position, it should stay there, but if it was scrolled to some index, keep it scrolled.

Thanks for the clarification.

**Comment by casper5822** [comment] 2019-06-07 15:31
i think that after unshift operation the scroll must stay in the same position, not scroll down to the previous item. 

Consider this scenario: 

I have other divs between the parentScroll element and the virtualscroller such as title, search bars, buttons and so on,  and i add (unshift) an item to the list, and the user is at scrollTop 0 (no movements from user, just stay here at the beginning of the pate). The virtual scroller changes the scroll position automatically after the unshift and i lost my current position from other divs between. The user sees the div moves alone (if for example it is a background unshift operation). So in my opinion, it's better to put a flag or property to switch off/on this behaviour. This actual behaviour is good for chat lists.

**Comment by casper5822** [comment] 2019-06-07 15:46
I agree with @jbonet. The behaviour is a problem if you have some content between the parentScroll component and the virtual-scroller for examples: search bars, titles and so on. If i am at 0 scrollPosition and i make a background unshift the user will see the page scroll down alone.

**Comment by speige** [comment] 2019-06-07 17:54
@casper5822 The code actually bypasses this feature if the current scroll position is 0.

I'm not sure I understand the UI examples of search bars/titles, I'm assuming they'd be fixed headers/footers, so the entire page wouldn't scroll, just the virtual items. Maybe I have the wrong picture in my head.

The problem with the previous approach before this issue was coded is that after unshift the visible items in the scroller would be random, which seems like an odd user experience. I can't imagine an app where that would be good. However, there are already apis for scrolling to a specific position/item/etc, so if anyone doesn't like this new behavior they can easily code around it in their specific app. If it was frequently being bypassed through custom code I would definitely add the flag, but I'd need to hear some real-world scenarios where this is happening before I know the flag is necessary.

This new feature has already been live for a month on npm (& the demo at https://rintoj.github.io/ngx-virtual-scroller), try it & see if it causes a problem for your app. So far I haven't seen any actual complaints, just "speculation" that it might be bad in some random scenario.

**Comment by casper5822** [comment] 2019-06-07 18:27
I try to explain my scenario: 

i have a div with a reference variable. Inside there is a card that contains search bar, header and than a table with the virtual-scroller with the parentScroll set to a root div that is before the card.

Like this:

```
<div #scroller>  <!-- this is my scroller div -->

  <div class="card">
        <div class="header">
          <h4 class="title">Title</h4>
          <br>
          <div class="row">
            <div class="col-md-5 col-md-offset-7 col-lg-4 col-lg-offset-8">
              <div class="input-group border-input" style="margin-bottom:20px;margin-top:15px;">
                <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                <input type="text" class="form-group form-control border-input" [(ngModel)]="searchText">
              </div>
            </div>
          </div>
        </div>

        <div class="content table-responsive table-full-width" style="padding-bottom:55px;">

          <virtual-scroller #scroll [items]="archivio" [parentScroll]="scroller">

            <table class="table"></table>

         </virtual-scroller>
        </div>
 </div>
</div>
```
-------------------------------

Consider this initial situation:

The user is at the root of the page and there is already an item in the table.
The virtual scroller has viewPortInfo.scrollStartPosition set to 0.
 
When an unshift is made, the virtual scroller moves directly to the "old" first table item in the table so all the page scrolls down also the card  part to the item in the table. 

 I made different test on this situation. So in this case the feature is not bypassed and the both scrollStartPosition and scroller.nativeElement.scrollTop are 0.

Maybe i made some mistake?

Thank you in advance.

My version is 3.0.1

**Comment by speige** [comment] 2019-06-07 18:50
@casper5822 Ok. I'll look into it & get back to you. Thanks for the explanation.

**Comment by casper5822** [comment] 2019-06-09 19:56
This is a workaround to unshift problem, and to have the desired behaviour. For me it works, hope also for you:

  this.scroller.viewPortItems = []; <- clear the viewPortItems
  this.results.unshift(newItem); <- make the ushift int the original list
  this.scroller.viewPortItems = this.results; <- assign again the list 

In this way, no scroll occurs for me.

Best regards

**Comment by speige** [comment] 2019-06-10 07:51
@casper5822 your suggestion has some problems. viewPortItems is intended to be readonly. It is what renders the actual items to the screen. By assigning the entire results array to it, you're disabling virtual scrolling & instead rendering all items.

Sorry I haven't gotten around to a proper fix yet. I've been busy.

**Comment by casper5822** [comment] 2019-06-10 09:43
@speige , thank you for the response and the clarification. No problem, i try only to give my contribuite because this component is amazing and works very well, also better than the angular official virtual scroller. 
I updated my workaround with according your information. I think now it is good:
I made a timeout only if when the scrollTop is 0 and in this case it will be always 0 as described in my test above. 
I made a simple templateRef  scrollTop = 0 after some time, ( i tried also with scroller.scrollToPosition(0,0) but it not works)

This is my code: 

 ```
 this.spinnerService.loader.show = true; 
                    
this.results.unshift(item);

                    if(this.mainPanelRef.nativeElement.scrollTop == 0){
                      setTimeout(()=>{
                        this.mainPanelRef.nativeElement.scrollTop = 0;
                        this.spinnerService.loader.show = false;
                      },450);
                    }
```

**Comment by casper5822** [comment] 2019-06-13 16:42
@speige  is there any new about this problem? Or a more clever fix that i can use without the timeout?
Thanks

**Comment by speige** [comment] 2019-06-13 22:20
@casper5822 Please try version 3.0.2 from npm. I believe I fixed the issue where it was keeping existing item focused even if scrollTop was 0.

**Comment by casper5822** [comment] 2019-06-14 07:31
@speige i tested the 3.0.2 it works like a charms. So great job. Thank you. 
For me it is the desired behaviour.

**Comment by jbonet** [comment] 2019-06-14 07:42
Thank you @speige. Now it is behaving as I expected.

**Closed** 2020-02-27 10:04 UTC
