### ISSUE TITLE
export 'Tween' was not found in '@tweenjs/tween.js'

### ISSUE THREAD

**Issue by patty3112** [rintoj/ngx-virtual-scroller#342] opened 2019-06-10 09:24 UTC
Currently i'm using ngx-virtual-scroller with storybook. Getting warning like
export 'Tween' was not found in '@tweenjs/tween.js'
export 'Easing' was not found in '@tweenjs/tween.js'

Version:
angular: 6
ngx-virtual-scroller: 3.0.1

Please help me with this, i'm I missing something here.

Thanks & Regards,
Pratik

**Comment by speige** [comment] 2019-06-10 10:02
Closing. This is a duplicate of several previously closed issues. Please read through those to find a resolution. Please reopen if you're still unable to resolve it.

**Closed by speige** 2019-06-10 10:02 UTC
