### ISSUE TITLE
Scrolling up causes crashing and bad performance

### ISSUE THREAD

**Issue by tmk1991** [rintoj/ngx-virtual-scroller#325] opened 2019-05-09 04:13 UTC
For some reason, scrolling up on large lists > 500 items causes flickering and eventually crashing. Scrolling downward works flawlessly.

` <virtual-scroller
    #scroll
    [items]="docs"> <div #container>
      <div class="infinite-item" *ngFor="let d of scroll.viewPortItems">
          {{d}}
      </div>
    </div>
  </virtual-scroller>`

**Comment by speige** [comment] 2019-05-09 12:52
Are you able to reproduce this on any of the examples here? https://rintoj.github.io/ngx-virtual-scroller  (click on the samples link).

Those samples only have 1000 items, but I have a personal project with lists of 30,000. I believe you're doing something wrong, because this is working flawlessly for me. 

The code you pasted looks fine, however it isn't enough to diagnose your problem. Could you create a stackblitz? The stackblitz should be as close to your real project as possible & needs to actually reproduce the problem.

Without looking at your code, it's really hard to guess what you're doing wrong. However, my first suggestion would be to convert to using OnPush Detection strategy. You can read my explanation in th readme here: https://github.com/rintoj/ngx-virtual-scroller#angular-onpush-detection-strategy---general-performance-advice-not-specific-to-ngx-virtual-scroller

**Comment by tmk1991** [comment] 2019-05-09 14:16
I completely understand. Hard to troubleshoot code you can't see. There's no doubt I'm doing something wrong. I can investigate reproducing.

I was passing in the parent scroller and when I took this out it would scroll up and down okay HOWEVER... from debugging, I notice that now ALL of the items are being rendered to the DOM. This also causes super slow scrolling and eventually breaks my app. 

**Thoughts on these possible things i'm doing wrong / ideas?:**

- 1000 items come into the array i'm passing into [items] at one time and the array is of objects with that 7-10 different properties/keys.
- I set my virtual-scroller css to height: 100vh

In the meantime, I'll also look at that OnPush strategy, I considered this too before posting.

**I have the same scroller in 8 other places in my app and it's working beautifully (so thank you!). This is much better than the ion-virtual-scroll and the angular CDK.**

**Comment by speige** [comment] 2019-05-09 14:30
All of the items shouldn't be rendered to the DOM, only the visible ones. That's definitely part of the problem.

Giving virtual-scroller css height: 100vh should be fine as long as it's the actual scroll element. If you're doing a parent scroll (for example: using window scrollbar), then virtual-scroller height shouldn't be constrained & instead the parent (html/body) should have a fixed height (typically 100% for html/body).

An array of objects for the [items[ array should be fine. Virtual-Scroller accepts any array, it doesn't care what data is inside of it.

I think if you read through the instructions carefully or look at the examples, you'll be able to figure out what you're doing wrong.

Closing for now. If you're unable to figure it out, please re-open with a stackblitz & i'll take a look.

**Closed by speige** 2019-05-09 14:30 UTC

**Comment by tmk1991** [comment] 2019-05-09 20:29
I figured it out.... 

I had a switch in the code.
<ng-container [ngSwitch]="libraryType">
              <ng-container *ngSwitchCase="librarySvc.LibrayItemTypes.EXERCISE">
                             .... 

I wrapped my component with a <div> and voila...  

This is the best infinite scroll on the market for angular BY FAR.
